### ISSUE TITLE
Number conversion does not work correctly

### ISSUE THREAD

**Issue by Gineus** [marcflohrer/stiebel-eltron-dashboard#112]
I just checked out the project, built it and let the unit test run. 28 of them are failing.

I guess the problem is, that I have "English" as my OS language. I guess the problem is in line 32 of `ValueParser`:

`var result = double.Parse(number.ToString());`

I guess the web site must be parsed as well for the current language `content-language` and then the code could be changed to

`var result = double.Parse(number.ToString(), currentWebPageCulture);`

I can prepare a fix if you want.

**Comment by marcflohrer** [comment]
Pull request is merged. Closing.
